// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FineCodeCoverage
{
    internal sealed partial class Vsix
    {
        public const string Id = "2019VSIssue1663280";
        public const string Name = "VS Issue 1663280";
        public const string Description = @"https://developercommunity.visualstudio.com/t/vsix-tool-window-vs2022-different-instantiation-wh/1663280";
        public const string Language = "en-US";
        public const string Version = "1.0.0";
        public const string Author = "Tony Hallett";
        public const string Tags = "";
    }
}
